name: go_to_isolate
description: A isolate thread pool.
version: 1.0.0
repository: https://github.com/snowmerak/go

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
